export const FormActionTypeEnum = {
    CREATE_REQUEST: 'FORM_CREATE_REQUEST',
    CREATE_SUCCESS: 'FORM_CREATE_SUCCESS',
    CREATE_FAIL: 'FORM_CREATE_FAIL',
    RESET_API_STATE: 'TAG_RESET_API_STATE',
}
